# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "new_app"
client_id = "2301191906fff9d026fae07a0f9180b9"
application_url = "https://largest-causing-anthony-trademark.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://largest-causing-anthony-trademark.trycloudflare.com/auth/callback",
  "https://largest-causing-anthony-trademark.trycloudflare.com/auth/shopify/callback",
  "https://largest-causing-anthony-trademark.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-6c10ea49.myshopify.com"
  